const enStopWords = {"a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "aren't", "as",
  "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "can't",
  "cannot", "could", "couldn't", "did", "didn't", "do", "does", "doesn't", "doing", "don't", "down",
  "during", "each", "few", "for", "from", "further", "had", "hadn't", "has", "hasn't", "have", "haven't",
  "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself",
  "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "isn't", "it", "it's",
  "its", "itself", "let's", "me", "more", "most", "mustn't", "my", "myself", "no", "nor", "not", "of", "off",
  "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same",
  "shan't", "she", "she'd", "she'll", "she's", "should", "shouldn't", "so", "some", "such", "than",
  "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's",
  "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too",
  "under", "until", "up", "very", "was", "wasn't", "we", "we'd", "we'll", "we're", "we've", "were",
  "weren't", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's",
  "whom", "why", "why's", "with", "won't", "would", "wouldn't", "you", "you'd", "you'll", "you're",
  "you've", "your", "yours", "yourself", "yourselves"};

const trStopWords = {"a", "acaba", "altı", "altmış", "ama", "ancak", "arada", "aslında", "ayrıca", "az",
  "bana", "bari", "bazen", "bazı", "bazıları", "belki", "ben", "benden", "beni", "benim",
  "beri", "beş", "bile", "bin", "bir", "biraz", "birçoğu", "birçok", "biri", "birisi",
  "birkaç", "birkez", "birşey", "birşeyi", "biz", "bizden", "bize", "bizi", "bizim",
  "böyle", "böylece", "bu", "buna", "bunda", "bundan", "bunlar", "bunları", "bunların",
  "bunu", "bunun", "burada", "bütün", "çoğu", "çok", "çünkü", "da", "daha", "dahi",
  "dan", "de", "defa", "değil", "diğer", "diğeri", "diğerleri", "diye", "doksan", "dokuz",
  "dolayı", "dolayısıyla", "dört", "edecek", "eden", "ederek", "edilecek", "ediliyor",
  "edilmesi", "ediyor", "eğer", "elbette", "elli", "en", "etmesi", "etti", "ettiği",
  "ettiğini", "fakat", "falan", "filan", "gene", "gereği", "gerek", "gibi", "göre", "hala",
  "halde", "halen", "hangi", "hangisi", "hani", "hatta", "hem", "henüz", "hep", "hepsi", "her","ve",
  "herhangi", "herkes", "herkese", "herkesi", "herkesin", "hiç", "hiçbir", "i", "ı", "için"};

const ruStopWords = {"а", "без", "более", "больше", "будет", "будто", "бы", "был", "была", "были",
  "было", "быть", "в", "вам", "вами", "вас", "ваш", "вдруг", "ведь", "весь",
  "во", "вот", "впрочем", "все", "всегда", "всего", "всех", "всю", "вы", "где",
  "да", "даже", "для", "до", "должен", "другая", "другие", "других", "другое", "другой",
  "её", "его", "едва", "если", "есть", "ещё", "же", "жизнь", "за", "зачем",
  "здесь", "и", "из", "или", "им", "именно", "иметь", "их", "к", "каждая",
  "каждое", "каждые", "каждый", "как", "какая", "какой", "когда", "кого", "ком", "кому",
  "которая", "которого", "которое", "которые", "который", "которых", "кто", "куда", "ли", "либо",
  "лучше", "между", "меня", "мне", "много", "может", "можно", "мой", "мочь", "мы",
  "на", "над", "надо", "наконец", "нас", "наш", "не", "него", "недавно", "нее",
  "ней", "нельзя", "нет", "ни", "нибудь", "ниже", "ним", "них", "ничего", "но",
  "ну", "о", "об", "один", "одна", "одни", "одного", "одной", "около", "он",
  "она", "они", "оно", "опять", "особенно", "от", "перед", "по", "под", "после",
  "потом", "потому", "почему", "почти", "при", "про", "раз", "разве", "с", "сам",
  "свое", "своего", "своей", "свои", "свой", "себе", "себя", "сегодня", "сейчас", "си",
  "сказал", "сказала", "сказать", "слишком", "со", "совсем", "так", "такая", "также", "таки",
  "такой", "там", "тебе", "тебя", "тем", "теперь", "то", "тогда", "того", "тоже",
  "той", "только", "том", "тот", "три", "тут", "ты", "у", "уж", "уже",
  "хорошо", "хотя", "чего", "чей", "чем", "через", "что", "чтобы", "чье", "чья",
  "эта", "эти", "это", "этого", "этой", "этом", "этот", "эту", "я"};