const enStopWords = {
  "i","me","my","myself","we","our","ours","ourselves","you","your","yours","yourself","yourselves",
  "he","him","his","himself","she","her","hers","herself","it","its","itself","they","them","their",
  "theirs","themselves","what","which","who","whom","this","that","these","those","am","is","are",
  "was","were","be","been","being","have","has","had","having","do","does","did","doing","a","an",
  "the","and","but","if","or","because","as","until","while","of","at","by","for","with","about",
  "against","between","into","through","during","before","after","above","below","to","from","up",
  "down","in","out","on","off","over","under","again","further","then","once","here","there","when",
  "where","why","how","all","any","both","each","few","more","most","other","some","such","no","nor",
  "not","only","own","same","so","than","too","very","s","t","can","will","just","don","should","now",
  "d","ll","m","o","re","ve","y","ain","aren","couldn","didn","doesn","hadn","hasn","haven","isn",
  "ma","mightn","mustn","needn","shan","shouldn","wasn","weren","won","wouldn","a's","able","according","accordingly","across","actually","afterwards","ain't",
  "allow","allows","almost","alone","along","already","also","although","always","among",
  "amongst","another","anybody","anyhow","anyone","anything","anyway","anyways","anywhere",
  "apart","appear","appreciate","appropriate","aren't","around","aside","ask","asking",
  "associated","available","away","awfully","b","became","become","becomes",
  "becoming","beforehand","behind","believe","beside","besides","best","better",
  "beyond","brief","c","came","cannot","cant","cause","causes",
  "certain","certainly","changes","clearly","co","com","come","comes","concerning","consequently",
  "consider","considering","contain","containing","contains","corresponding","could","couldn't",
  "course","currently","dare","definitely","described","despite","didn't","different","doesn't","don't","done","downwards",
  "edu","eg","eight","either",
  "else","elsewhere","enough","entirely","especially","et","etc","even","ever","evermore","every",
  "everybody","everyone","everything","everywhere","ex","exactly","example","except","f","fairly",
  "far","farther","fifth","first","five","followed","following","follows","forever",
  "former","formerly","forth","forward","found","four","furthermore","g","get","gets","getting",
  "given","gives","go","goes","going","gone","got","gotten","greetings","hadn't","happens",
  "hardly","hasn't","haven't","he's","hello","help","hence","here's",
  "hereafter","hereby","herein","hereupon","hi","hither","hopefully",
  "howbeit","however","hundred","i'd","i'll","i'm","i've","ie","ignored","immediate","inasmuch",
  "inc","indeed","indicate","indicated","indicates","inner","insofar","instead","inward",
  "isn't","it'd","it'll","it's","k","keep","keeps","kept","know","known",
  "knows","l","last","lately","later","latter","latterly","least","less","lest","let","let's","like",
  "liked","likely","likewise","little","look","looking","looks","low","lower","ltd","made","mainly",
  "make","makes","many","may","maybe","meantime","meanwhile","merely","might","mine","minus","miss",
  "moreover","mostly","much","must","name","namely","nd","near","nearly","necessary",
  "need","needs","neither","never","nevertheless","new","next","nine","no-one","nobody","non","none",
  "nonetheless","noone","nothing","notwithstanding","novel","nowhere","obviously","often",
  "oh","ok","okay","old","ones","onto","opposite","others","otherwise",
  "ought","outside","overall","particular","particularly",
  "per","perhaps","placed","please","plus","possible","presumably","probably","provided","provides",
  "q","que","quite","qv","r","rather","really","reasonably","regarding","regardless",
  "regards","relatively","respectively","right","round","said","saw","say","saying",
  "says","second","secondly","see","seeing","seem","seemed","seeming","seems","seen","self",
  "selves","sensible","sent","serious","seriously","seven","several","shall","shan't","she'd",
  "she'll","she's","shouldn't","since","six","somebody","somehow","someone","something",
  "sometime","sometimes","somewhat","somewhere","soon","sorry","specified","specify","specifying",
  "still","sub","sup","sure","take","taken","taking","tell","tends","th","thank",
  "thanks","thanx","that'll","that's","thats","there's","thereafter","thereby",
  "therefore","therein","theres","thereupon","they'd","they'll","they're","they've","think",
  "third","thirty","thorough","thoroughly","though","three","throughout","thru","thus",
  "together","took","toward","towards","tried","tries","truly","try","trying","twice","two",
  "u","un","underneath","undoing","unfortunately","unless","unlike","unlikely","unto",
  "upon","upwards","us","use","used","useful","uses","using","usually","v","value","various",
  "versus","via","viz","vs","w","want","wants","wasn't","way","we'd","we'll","we're","we've",
  "welcome","well","went","weren't","what's","whatever","when's","whence","whenever","where's",
  "whereafter","whereas","whereby","wherein","whereupon","wherever","whether","whichever",
  "whither","who's","whoever","whole","whose","why's","willing","wish",
  "within","without","wonder","won't","wouldn't","yes","yet","you'd","you'll","you're",
  "you've","z","zero"};

const ruStopWords = {
  "а", "без", "более", "больше", "будем", "будет", "будете", "будешь", "будто",
  "буду", "будут", "бы", "был", "была", "были", "было", "быть", "в", "вам",
  "вами", "вас", "вдруг", "ведь", "во", "вот", "впрочем", "все", "всё", "всего",
  "всех", "вся", "всё-таки", "вы", "где", "да", "даже", "для", "до", "должен",
  "должна", "должно", "должны", "если", "её", "его", "едва", "ей", "ему", "еще",
  "ещё", "ею", "же", "за", "зачем", "здесь", "из", "или", "им", "ими", "их", "к",
  "каждая", "каждое", "каждые", "каждый", "как", "какая", "какие", "каким",
  "какими", "каких", "какое", "когда", "кого", "ком", "кому", "которая",
  "которого", "которой", "которые", "который", "которых", "кто", "куда", "ли",
  "либо", "лишь", "мне", "много", "может", "можно", "мой", "моя", "моё", "мои",
  "мы", "на", "над", "надо", "наконец", "нас", "наш", "наша", "наше", "наши",
  "не", "него", "нее", "неё", "ней", "нельзя", "нет", "ни", "ниже",
  "них", "но", "ну", "о", "об", "однако", "он", "она", "они", "оно", "от", "перед",
  "по", "под", "после", "потому", "почти", "при", "про", "раз", "разве", "с",
  "сам", "сама", "сами", "самим", "самими", "самих", "само", "самого", "самой",
  "самом", "самому", "саму", "свое", "своего", "своей", "своем", "своему",
  "своё", "свои", "свой", "своих", "своим", "своими", "себе", "себя", "сейчас",
  "со", "так", "такая", "также", "такие", "такой", "там", "те", "тем", "теми",
  "тех", "то", "тогда", "того", "тоже", "только", "том", "тот", "три", "тут",
  "ты", "у", "уж", "уже", "хоть", "чего", "чем", "через", "что", "чтоб", "чтобы",
  "чье", "чьё", "чьего", "чьей", "чьем", "чьём", "чьему", "чью", "эта", "эти",
  "этим", "этими", "этих", "это", "этого", "этой", "этом", "этому", "этот", "эту",
  "я", "ихний", "ваша", "ваш", "твой", "твоя", "твоё", "твои",
  "будучи", "ведомо", "между", "чуть", "вдоль", "всюду", "вокруг", "против",
  "около", "рядом", "из-за", "из-под", "пока", "пусть", "всё же",
  "как-то", "оттого", "иначе", "так-то", "ужели", "едва ли",
  "словно", "будто бы", "прямо", "вроде", "мол", "якобы", "вне",
  "поэтому", "отсюда", "зато", "хотя"
};

const trStopWords = {
  "a", "acaba", "ama", "ancak", "artık", "asla", "aslında", "az", "bana", "bazen",
  "bazı", "bazıları", "belki", "ben", "beni", "benim", "beri", "beş", "bile",
  "bilhassa", "bir", "birçok", "birçoku", "biri", "birisi", "birkaç", "birşey",
  "biz", "bize", "bizi", "bizim", "bu", "buna", "bunda", "bundan", "bunlar",
  "bunları", "bunların", "bunu", "bunun", "burada", "bütün", "çoğu", "çoğunu",
  "çok", "çünkü", "da", "daha", "dahi", "de", "defa", "değil", "diğer", "diye",
  "doksan", "dokuz", "dolayı", "dolayısıyla", "dört", "edecek", "eden", "ederek",
  "edilecek", "ediliyor", "edilmesi", "ediyor", "eğer", "elbette", "elli", "en",
  "etmesi", "etti", "ettiği", "ettiğini", "fakat", "falan", "filan", "gibi", "göre",
  "halen", "hangi", "hatta", "hem", "henüz", "hep", "hepsi", "her", "herhangi",
  "herkes", "herkese", "herkesi", "hiç", "hiçbir", "için", "içinde", "iki", "ile",
  "ilgili", "ise", "işte", "itibaren", "itibariyle", "kadar", "karşın", "kendi",
  "kendine", "kendini", "kez", "ki", "kim", "kime", "kimi", "kimse", "kırk",
  "madem", "mı", "mi", "mu", "mü", "nasıl", "ne", "neden", "nedir", "nerde",
  "nerede", "nereye", "niçin", "niye", "o", "olan", "olarak", "oldu", "olduğu",
  "olduğunu", "oldukça", "olmadı", "olmadığı", "olmak", "olması", "olmayan",
  "olmaz", "olsa", "olsun", "olup", "olur", "olursa", "oluyor", "on", "ona",
  "ondan", "onlar", "onlara", "onlardan", "onları", "onların", "onu", "onun",
  "orada", "oysa", "pek", "rağmen", "sana", "sanki", "sekiz", "seksen", "sen",
  "senden", "seni", "senin", "siz", "sizde", "sizden", "size", "sizi", "sizin",
  "şayet", "şey", "şeyden", "şeyi", "şeyler", "şöyle", "şu", "şuna", "şunda",
  "şundan", "şunlar", "şunu", "şunun", "tarafından", "trilyon", "tüm", "üç",
  "üzere", "var", "vardı", "ve", "veya", "ya", "yani", "yapacak", "yapılan",
  "yapılması", "yapıyor", "yapmak", "yaptı", "yaptığı", "yaptığını", "yedi",
  "yerine", "yetmiş", "yine", "yirmi", "yok", "yüz", "zaten", "zira"
};

